# Generated by Django 5.1.6 on 2025-03-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_alter_dish_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guests',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
